import { TeamMember } from "@/types/TeamRoster";

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "1",
    name: "Ghadi",
    role: "FOUNDER & CEO",
    avatar: "G",
    avatarColor: "bg-yellow-500",
    tasksActive: 12,
    compliance: 98,
    status: "ready",
  },
  {
    id: "2",
    name: "Eli",
    role: "STRATEGIC ADVISOR & MENTOR",
    avatar: "E",
    avatarColor: "bg-yellow-500",
    tasksActive: 12,
    compliance: 98,
    status: "locked",
  },
  {
    id: "3",
    name: "Head of Growth",
    role: "OPERATIONS LEAD",
    avatar: "HG",
    avatarColor: "bg-blue-500",
    tasksActive: 8,
    compliance: 95,
    status: "ready",
  },
  {
    id: "4",
    name: "Amama",
    role: "TECHNICAL DIRECTOR",
    avatar: "A",
    avatarColor: "bg-purple-500",
    tasksActive: 10,
    compliance: 92,
    status: "ready",
  },
  {
    id: "5",
    name: "Talha AI",
    role: "AUTOMATION ENGINEER",
    avatar: "TA",
    avatarColor: "bg-green-500",
    tasksActive: 15,
    compliance: 97,
    status: "ready",
  },
  {
    id: "6",
    name: "Mobile Dev Lead",
    role: "PRODUCT DEVELOPMENT",
    avatar: "MD",
    avatarColor: "bg-red-500",
    tasksActive: 9,
    compliance: 94,
    status: "ready",
  },
  {
    id: "7",
    name: "UI/UX Lead",
    role: "DESIGN & BRAND",
    avatar: "UX",
    avatarColor: "bg-cyan-500",
    tasksActive: 7,
    compliance: 96,
    status: "ready",
  },
];
